resources:
  tb:securityhub:SecurityHubAccount:
    options:
      autoEnableControls: true
      enableDefaultControls: true
  tb:securityhub:GuardDutyConfiguration:
    features:
      - name: "S3_DATA_EVENTS"
        status: "ENABLED"
      - name: "EKS_AUDIT_LOGS"
        status: "DISABLED"
      - name: "RUNTIME_MONITORING"
        status: "ENABLED"
        additional_configurations:
          - {
              'name': 'ECS_FARGATE_AGENT_MANAGEMENT',
              'status': 'ENABLED',
            }
          - {
              'name': 'EC2_AGENT_MANAGEMENT',
              'status': 'ENABLED',
            }
      # - name: "EKS_RUNTIME_MONITORING"
      #   status: "DISABLED"
      #   additional_configurations:
      #     - {
      #         'name': 'EKS_ADDON_MANAGEMENT',
      #         'status': 'DISABLED',
      #       }
      - name: "EBS_MALWARE_PROTECTION"
        status: "ENABLED"
      - name: "RDS_LOGIN_EVENTS"
        status: "ENABLED"
      - name: "LAMBDA_NETWORK_LOGS"
        status: "ENABLED"
      # - name: "FLOW_LOGS"
      #   status: "ENABLED"